### PR TITLE
feat: compression of files with less than 256 indexes

### PR DESCRIPTION
**Pull request by TheNuclearNexus**
This PR compresses the vertex index area by combining the position index and uv index into one pixel instead of using 2. It automatically applies when there are less than 256 UVs. The shader handles the tweaked format and the original automatically so this is non breaking to the current release.

* My formatter changed the formatting of the main python file, not sure if that's an issue or not.

### CODE REVIEW

**Comment by Godlander** [comment]
i agree that the data format is not very optimal and there is a lot of wasted space
but i dont think splitting the format into two is a good solution

**Comment by TheNuclearNexus** [comment]
I don't think its too unusual to apply a different kind of compression which best suits the data, at least this way crazy large models can still have all of their things and smaller mc models can benefit from a super large file size reduction

**Review by Godlander — CHANGES_REQUESTED** [review]
remove unused iviewrotmat uniform

**Review by Godlander — CHANGES_REQUESTED** [review]
update minimum version

**Comment by Godlander** [comment]
man how does this review thing work lol, i keep accidentally doing stuff

**Comment by TheNuclearNexus** [comment]
> remove unused iviewrotmat uniform

Entities still use it in some places, should they not?

**Comment by Godlander** [comment]
the only place i think still uses it is end sky

**Pull request merged**
