### PR TITLE
Command arguments system

### PR DESCRIPTION
**Pull request by kumitatepazuru**
A system that allows settings to be specified as arguments, using argparse (standard library)
This will improve usability, as you can see the list of arguments when you add --help at runtime, and there is no need to change variables in the file.
Also, since we are using the standard library, there is no need for users to add libraries, and the additional code used in this system is short, so developers can be flexible as they move forward.

### CODE REVIEW

**Comment by Godlander** [comment]
i think this is a good idea, but I'm a bit hesitant to add it for now due to how much I expect the input format to change as I add more stuff.

**Comment by kumitatepazuru** [comment]
We've applied this update to support new options, including flipuv.

**Comment by Godlander** [comment]
is it possible to somehow keep the current list of options in the script, but allow args to overwrite them?

**Comment by Godlander** [comment]
ah maybe like this?
if this works i think i like it more
```py
duration = 20

parser.add_argument('--duration', type=int, help="Spectify a duration", default=duration)
duration = args.duration
```

**Comment by Godlander** [comment]
nice it did work, iv put it into latest update along with fixes for new fog as well as a more flexible colorbehavior

**Pull request closed without merging**
