### PR TITLE
Config system

### PR DESCRIPTION
**Pull request by bogdikon**
I made config system to prevent code corruption and modify config easily

### CODE REVIEW

**Comment by Godlander** [comment]
not sure if requiring even more files as input would help with the already fairly un-user friendly process, plus i'm not certain on the format, will change a lot of things around, and it'll just get more confusing for me.

for example i just added an easing option, and will probably change that to allow per-frame easing setting.

ultimately a gui would be ideal but that's not on the table now (or even in the house)

**Comment by bogdikon** [comment]
> not sure if requiring even more files as input would help with the already fairly un-user friendly process, plus i'm not certain on the format, will change a lot of things around, and it'll just get more confusing for me.
> 
> for example i just added an easing option, and will probably change that to allow per-frame easing setting.
> 
> ultimately a gui would be ideal but that's not on the table now (or even in the house)

I think I can work with GUI, I just need some time (but I can)

**Comment by Godlander** [comment]
again, do expect format and options to change a lot.

i wouldnt worry too much about it for now.

i'd also like to avoid adding more libraries that user would need to manually install, because adding an extra step to remove a step isnt really doing much. but i think that probably wont be possible.

another idea is to it into an executable, but that might run into os compatibility issues

**Comment by Godlander** [comment]
closing since i decided to use argparse for command line arguments as input.
the script can still be edited and the options set there will be treated as default.

**Pull request closed without merging**
